version: 1.0.{build}
image:
- Visual Studio 2013
- Visual Studio 2015
configuration:
- Debug
- Release
platform:
- Any CPU
before_build:
- cmd: nuget restore
build:
  project: Sharpener.sln
  parallel: true
  verbosity: minimal
cache:
- packages -> **\packages.config
- '%LocalAppData%\NuGet\Cache'